
//EMAILDATA
export const GET_EMAILDATA_SUCCESS = "GET_EMAILDATA_SUCCESS";
export const GET_EMAILDATA_FAIL = "GET_EMAILDATA_FAIL";
export const UPDATE_EMAILDATA_SUCCESS = "UPDATE_EMAILDATA_SUCCESS";
export const UPDATE_EMAILDATA_FAIL = "UPDATE_EMAILDATA_FAIL";



