//EMAILDATA
export const GET_EMAILDATA_SUCCESS = "GET_EMAILDATA_SUCCESS";
export const GET_EMAILDATA_FAIL = "GET_EMAILDATA_FAIL";
export const UPDATE_EMAILDATA_SUCCESS = "UPDATE_EMAILDATA_SUCCESS";
export const UPDATE_EMAILDATA_FAIL = "UPDATE_EMAILDATA_FAIL";
export const LOG_EMAILDATA_ERROR = "LOG_EMAILDATA_ERROR";
export const CLEAR_EMAILDATA_ERROR = "CLEAR_EMAILDATA_ERROR";
