//ROOMS
export const GET_ROOMS = "GET_ROOMS";
export const STORE_CURRENT_ROOM = "STORE_CURRENT_ROOM";
export const LOG_ROOM_ERROR = "LOG_ROOM_ERROR";

export const GET_ROOMS_ERROR = "GET_ROOMS_ERROR";
export const CREATE_EDIT_ROOM_ERROR = "CREATE_EDIT_ROOM_ERROR";
export const DELETE_ROOM_ERROR = "DELETE_ROOM_ERROR";


